version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^tests:"
      - "^.github:"
      - "^.vscode:"

scoops:
  - name: terrable
    url_template: "https://github.com/terrable-dev/terrable/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    directory: bucket
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"

    repository:
      owner: terrable-dev
      name: scoop
      branch: main

brews:
  - name: terrable
    url_template: "https://github.com/terrable-dev/terrable/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    directory: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    commit_msg_template: "Homebrew update for {{ .ProjectName }} version {{ .Tag }}"

    repository:
      owner: terrable-dev
      name: tap
      branch: main
