name: GoReleaser Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  go-releaser-release:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.ACTIONS_APP_ID }}
          private_key: ${{ secrets.ACTIONS_APP_PRIVATE_KEY }}

      - name: GoReleaser release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
  